POST /customers
Host: localhost:8080
Content-Type: application/json

{
  "firstName" : "rodi",
  "lastName": "m",
  "budget": 99
}

###

GET /customers
Host: localhost:8080
Content-Type: application/json

### FLAW

GET /flaws/injection/customerId/' or '1'='1
Host: localhost:8080

### FIX

GET /flaws/injection/customerId/fix/' or '1'='1
Host: localhost:8080

###

GET /flaws/injection/customerId/fix/8fb78b55-3430-4f02-b988-67e49371efdf
Host: localhost:8080
