POST /customers
Host: localhost:8080
Content-Type: application/json

{
  "firstName" : "rodi",
  "lastName": "m",
  "budget": 99
}

###

GET /customers
Host: localhost:8080
Content-Type: application/json

###

GET /flaws/injection/' or '1'='1
Host: localhost:8080
